name: gif_picker
description: Gif picker using Tenor official API's.
version: 1.0.0+1
homepage: https://github.com/koiralapankaj7/gif_picker

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
